platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'xyTV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 5.5'
  pod  'SnapKit' ,  '~> 5.0.0' 

pod 'NVActivityIndicatorView'

  # Pods for xyTV

  target 'xyTVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'xyTVUITests' do
    # Pods for testing
  end

end
